In [2]:
#pip install numpy

In [3]:
import numpy as np

To get the documentation:
    
Shift + Tab

## Creating an Array

In [4]:
myList = [1, 2, 3, 4, 5]
myList

[1, 2, 3, 4, 5]

In [5]:
arr = np.array(myList) #One dimensional array/Vector
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
myNestedList = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(myNestedList) #Two dimensional array/Matrix
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2.shape

(3, 3)

In [9]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 10]

In [10]:
np.array([l1, l2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [12]:
np.arange(1, 101, 3)

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [13]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((5, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full((4, 5), 20)

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

## Random Arrays

In [22]:
np.random.randint(1, 100, 10)

array([39, 87, 75, 17, 32, 55, 52, 52, 70, 28])

In [24]:
randomArray = np.random.randint(1, 100, (10, 5))
randomArray

array([[60, 91, 53, 49, 64],
       [27, 91, 11, 60, 49],
       [ 6, 82, 95, 44, 24],
       [20, 73, 36, 96, 93],
       [49, 20, 23, 59, 90],
       [20, 23, 91, 73, 81],
       [ 4, 22, 27, 50, 91],
       [97, 64, 56,  5, 99],
       [10, 92, 25,  8, 15],
       [46, 39, 72, 47, 21]])

In [25]:
randomArray.min()

4

In [26]:
randomArray.max()

99

In [28]:
randomArray.dtype

dtype('int64')

## Reshaping Arrays

In [29]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr1.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr1.reshape(10, 5)

ValueError: cannot reshape array of size 25 into shape (10,5)

## Indexing

In [32]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr1[8]

8

In [34]:
arr1[10]

10

In [35]:
#[start=0: stop=len: step=1]
arr1[4:15]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
arr1[4:15:2]

array([ 4,  6,  8, 10, 12, 14])

In [37]:
arr1[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [39]:
arr1[::-2]

array([24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

## Indexing a Multi-Dimensional Array

In [49]:
randomArray

array([[60, 91, 53, 49, 64],
       [27, 91, 11, 60, 49],
       [ 6, 82, 95, 44, 24],
       [20, 73, 36, 96, 93],
       [49, 20, 23, 59, 90],
       [20, 23, 91, 73, 81],
       [ 4, 22, 27, 50, 91],
       [97, 64, 56,  5, 99],
       [10, 92, 25,  8, 15],
       [46, 39, 72, 47, 21]])

In [50]:
randomArray[2]

array([ 6, 82, 95, 44, 24])

In [51]:
randomArray[2][3]

44

## Fancy Indexing

In [52]:
randomArray[[4, 1]]

array([[49, 20, 23, 59, 90],
       [27, 91, 11, 60, 49]])

## Sorting Arrays

In [40]:
unsortedArr = np.array([45, 100, 10, 4, 5, 7, 34, 76])
unsortedArr

array([ 45, 100,  10,   4,   5,   7,  34,  76])

In [44]:
sortedList = sorted(unsortedArr)
sortedList

[4, 5, 7, 10, 34, 45, 76, 100]

In [42]:
unsortedArr.sort()

In [43]:
unsortedArr

array([  4,   5,   7,  10,  34,  45,  76, 100])

## Broadcasting

In [45]:
sortedList[:] = 50

TypeError: can only assign an iterable

In [46]:
unsortedArr[1:6] = 50

In [47]:
unsortedArr

array([  4,  50,  50,  50,  50,  50,  76, 100])

In [48]:
unsortedArr[:] = 100
unsortedArr

array([100, 100, 100, 100, 100, 100, 100, 100])

## Conditional Selection

In [53]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [55]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [56]:
(arr > 5) & (arr%2==0)

array([False, False, False, False, False, False,  True, False,  True,
       False,  True])

In [57]:
arr[(arr > 5) & (arr%2==0)]

array([ 6,  8, 10])

In [ ]:
#and - logical operator
#& - bitwise operator